.\" Process this file with
.\" groff -man -Tascii gwibber.1
.\"
.TH GWIBBER-POSTER 1 "JANUARY 2010" Linux "User Manuals"
.SH NAME
Gwibber \- Microblogging client for GNOME
.SH SYNOPSIS
.B gwibber-poster [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B Gwibber
is an open source microblogging client for GNOME developed with Python and GTK. It supports Twitter, Jaiku, Identi.ca, Facebook, Flickr, Digg, and RSS.
.SH OPTIONS
.IP "-h, --help"
Show help message and exit
.IP "-p, --persist"
Don't exit after posting
.IP "-w, --window"
Don't exit when the window loses focus, also implies -d
.IP "--decorate"
Display window decorations
.IP "-m, --message"
Message to post
.IP "-d, --debug"
Log debug messages
.SH BUGS
Please report all bugs to the Gwibber bug tracker:
http://bugs.launchpad.net/gwibber
.SH AUTHOR
Ken VanDine <ken.vandine@canonical.com>

Copyright 2010.  Licensed under a Creative Commons Attribution-ShareAlike License <http://creativecommons.org/licenses/by-sa/3.0/>
